### ISSUE TITLE
Unable to connect, process hangs at 'Requesting capability list...' in Quassel

### ISSUE THREAD

**Issue by rodneyrod** [pbui/irtelegramd#2]
OS: Debian Bullseye x86
Python version: 3.7

Steps to reproduce:
1. Install all modules listed in script through pip3
2. Run 'python3 irtelegramd.py'
3. Connect Quassel to 127.0.0.1:6667

Results:
Quassel will display 'Requesting capability list...' and go no further

The script generates the following error after a couple of minutes in the shell executing it:
```
[E 200110 12:00:34 ioloop:763] Exception in callback functools.partial(<function
 TCPServer._handle_connection.<locals>.<lambda> at 0xb63a1b24>, <Task finished c
oro=<IRCTelegramd.handle_stream() done, defined at irtelegramd.py:44> exception=
StreamClosedError('Stream is closed')>)
    Traceback (most recent call last):
      File "/home/telegram/.local/lib/python3.7/site-packages/tornado/ioloop.py"
, line 743, in _run_callback
        ret = callback()
      File "/home/telegram/.local/lib/python3.7/site-packages/tornado/tcpserver.
py", line 327, in <lambda>
        gen.convert_yielded(future), lambda f: f.result()
      File "irtelegramd.py", line 46, in handle_stream
        await handler.run()
      File "irtelegramd.py", line 83, in run
        message = await self.stream.read_until(b'\n')
    tornado.iostream.StreamClosedError: Stream is closed
```

**Comment by sambattalio** [comment]
I was having the same issue actually...

**Comment by AndroidKitKat** [comment]
I've had an issue similar to this but using thelounge.

**Comment by rodneyrod** [comment]
Tested, same issue on Alpine as well with the Docker file, just had to make sure.
